name: CI

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '15 3 * * 0'  # Every Sunday at 1:15pm Me;bourne (AEST/AEDT)

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
    env:
      MONGODB_TEST_URI: mongodb://localhost:27017/bloggy_test
      JWT_SECRET: test-secret
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - run: npm ci

      # Run tests, create JUnit logs for test results
      - run: |
          npm install jest-junit --no-save
          npm test -- --ci --reporters=default --reporters=jest-junit --outputFile=test-results.xml

      # Upload test results as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml